FROM apache/spark:3.5.0

USER root
RUN apt-get update && \
    apt-get install -y curl && \
    rm -rf /var/lib/apt/lists/*

CMD ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"] 